[build]
  command = "npm run build"
  publish = "_site"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    # Run Lighthouse on the entire site after build
    audits = ["accessibility", "best-practices", "performance", "pwa", "seo"]
    
    # Upload Lighthouse results to Netlify 
    upload = true
    
    # Set performance budget thresholds
    budgets = [
      {
        "resourceSizes" = [
          { "resourceType" = "total", "budget" = 500 }
        ],
        "resourceCounts" = [
          { "resourceType" = "total", "budget" = 100 }
        ]
      }
    ]
    
    # Fail build if performance scores are below thresholds
    settings = {
      "emulatedFormFactor" = "desktop",
      "throttlingMethod" = "simulate"
    }

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"